mm - cleanup: clarified test cases, cleaned up mater test.sh

diff --git a/test/build b/test/build
--- a/test/build
+++ b/test/build
@@ -1,10 +1,35 @@
 #!/bin/sh
 
-../falco -b -n skdjfhsdkjfhd -d ../vfeed.db
-echo $?
+state=0
+make clean > /dev/null
 
-make clean
-
-make all
-
-make clean
+# test for pass
+make nonexist.build.out
+if [ "$?" -gt 0 ]
+then
+    echo "build test: check for non existant package build test failed"
+    exit
+fi
+# test for fail
+make bash.build.out > /dev/null
+if [ "$?" -eq 0 ]
+then
+    echo "build test: check for known vulnerability in bash test failed"
+    exit
+fi
+#test for fail
+make multi.build.out > /dev/null
+if [ "$?" -eq 0 ]
+then
+    echo "build test: multi package build test failed"
+    exit
+fi
+# clean fails because the multipackage check file is not there
+make clean 
+if [ "$?" -eq 0 ]
+then
+    echo "      build test: all build feature tests succeeded"
+else
+    echo "build test: clean test failed"
+fi
+exit
diff --git a/test/database b/test/database
--- a/test/database
+++ b/test/database
@@ -1,5 +1,22 @@
 #!/bin/sh
 
-../falco -d ../vfeed.db -n sqlite
+../falco -d ../vfeed.db -n sqlite > /dev/null
+if [ "$?" -eq 0 ]
+then
+    echo "database existance test, PASS found database at ../vfeed.db"
+else
+    echo "database test, FAILED, did not find database at ../vfeed.db"
+    exit
+fi
 
-../falco -d ../xxxxvfeed.db -n sqlite
+# test for the non existance of the database xxxxvfeed.db does not exist
+../falco -d ../xxxxvfeed.db -n sqlite 2>&1 > /dev/null
+if [ "$?" -gt 0 ]
+then
+    echo "database test, PASS, logic failed to find database at xxxxvfeed.db"
+else
+    echo "database test, FAILED, did not alarm for nonexistent database xxxxvfeed.db"
+    exit
+fi
+
+
