working on getting json, html output looking nice, passing all tests in test framework.  Cleaned up code.

diff --git a/test/format b/test/format
--- a/test/format
+++ b/test/format
@@ -1,18 +1,32 @@
 #!/bin/sh
 
 echo "testing -t, type output, -t text:"
-../falco -t text -d ../vfeed.db -n python -v 2.7.3
-if [ "$?" -gt "0" ]
+../falco -t text -d ../vfeed.db -n python -v 2.7.3 
+if [ "$?" -gt 0 ]
 then
-    echo "format test: failed -t text test" -o /dev/null
+    echo "format test: failed -t text test"
     exit 1
+else:
+    echo "format test: passed -t text test"
 fi
 
 echo "testing -t, type output, -t json:"
-../falco -t json -d ../vfeed.db -n python -v 2.7.3 -o /dev/null
-if [ "$?" -gt "0" ]
+../falco -t json -d ../vfeed.db -n python -v 2.7.3
+if [ "$?" -gt 0 ]
 then
     echo "format test: failed -t json test"
     exit 1
+else:
+    echo "format test: passed -t json test"
+fi
+
+echo "testing -t, type output, -t html:"
+../falco -t html -d ../vfeed.db -n python -v 2.7.3
+if [ "$?" -gt 0 ]
+then
+    echo "format test: failed -t html test"
+    exit 1
+else:
+    echo "format test: passed -t html test"
 fi
 
diff --git a/test/workfile b/test/workfile
--- a/test/workfile
+++ b/test/workfile
@@ -1,5 +1,38 @@
 #!/bin/sh
 
-../falco -f testlist.txt -d ../vfeed.db
-../falco -t text -f testlist.txt -d ../vfeed.db
-../falco -t json -f testlist.txt -d ../vfeed.db
+echo "testing using -f testlist.txt"
+../falco -f testlist.txt -d ../vfeed.db > /dev/null
+if [ "$?" -gt 0 ]
+then
+    echo "\t-f textlist.txt failed"
+    exit 1
+else:
+    echo "\t-f textlist.txt passed"
+fi
+echo "testing using -t text -f testlist.txt"
+../falco -t text -f testlist.txt -d ../vfeed.db > /dev/null
+if [ "$?" -gt 0 ]
+then
+    echo "\t-t text failed"
+    exit 1
+else:
+    echo "\t-t text textlist.txt passed"
+fi
+echo "testing using -t json -f testlist.txt"
+../falco -t json -f testlist.txt -d ../vfeed.db -o /dev/null
+if [ "$?" -gt 0 ]
+then
+    echo "\t-t json failed"
+    exit 1
+else:
+    echo "\t-t json textlist.txt passed"
+fi
+echo "testing using -t html -f testlist.txt"
+../falco -t html -f testlist.txt -d ../vfeed.db > /dev/null
+if [ "$?" -gt 0 ]
+then
+    echo "-t html failed"
+    exit 1
+else:
+    echo "\t-t html textlist.txt passed"
+fi
