cleaning up test cases

diff --git a/test/packagename b/test/packagename
--- a/test/packagename
+++ b/test/packagename
@@ -1,4 +1,14 @@
 #!/bin/sh
+# test for the a non existant package (postgres) and one that 
+# exists, postgresql
+if [ "`../falco -d ../vfeed.db -n postgres | wc -l`" -gt 0 ]
+then
+    echo "packagename test failed, tested for postgres should not exist"
+    exit 1
+fi
+if [ "`../falco -d ../vfeed.db -n postgresql | wc -l`" -eq 0 ]
+then
+    echo "packagename test failed, tested for postgresql, should exist"
+    exit 1
+fi
 
-../falco -d ../vfeed.db -n postgres
-../falco -d ../vfeed.db -n postgresql
diff --git a/test/version b/test/version
--- a/test/version
+++ b/test/version
@@ -1,7 +1,15 @@
 #!/bin/sh
 
+function vtest {
+if [ "`../falco -d ../vfeed.db -n $1 -v $2 | wc -l`" -eq $3 ]
+then
+    echo "version: package $1, version $2 failed"
+    exit 1
+fi
+}
 echo "test for version 8"
-../falco -d ../vfeed.db -n postgresql -v 8
+#../falco -d ../vfeed.db -n postgresql -v 8
+vtest postgresql 8 1
 echo $?
 echo "test for version 8.0"
 ../falco -d ../vfeed.db -n postgresql -v 8.0
